use domain::{InstrumentDefinition,InstrumentId,SourceId,SourceKind,UnixNanos,VenueId};use fixed_decimal::{FixedDecimal,Notional,Price,Quantity,Rate};use serde::{Deserialize,Serialize};use thiserror::Error;
const EVENT_DOMAIN:&[u8]=b"cmti:event:v1\0";const MAX_LEVELS:usize=1_000_000;
#[derive(Clone,Debug,Eq,Error,PartialEq)]pub enum EventError{#[error("invalid metadata")]Metadata,#[error("missing raw hash")]MissingRawHash,#[error("sequence mismatch")]SequenceMismatch,#[error("invalid payload")]Payload,#[error("identity mismatch")]IdentityMismatch}
#[derive(Clone,Copy,Debug,Eq,Hash,PartialEq,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum SnapshotKind{NotApplicable,Snapshot,Delta}
#[derive(Clone,Copy,Debug,Eq,Hash,PartialEq,Serialize,Deserialize)]#[serde(transparent)]pub struct QualityFlags(u64);impl QualityFlags{pub const NONE:Self=Self(0);pub const STALE:Self=Self(1);pub const PARTIAL:Self=Self(2);pub const CLOCK_UNCERTAIN:Self=Self(4);pub const SOURCE_DEGRADED:Self=Self(8);pub const fn bits(self)->u64{self.0}}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct EventMetadata{pub schema_version:u32,pub source:SourceId,pub venue:Option<VenueId>,pub instrument_id:Option<InstrumentId>,pub exchange_timestamp:Option<UnixNanos>,pub receive_wall_timestamp:UnixNanos,pub receive_monotonic_ns:u64,pub connection_started_at:UnixNanos,pub sequence_number:Option<u64>,pub connection_epoch:u64,pub snapshot_kind:SnapshotKind,pub source_checksum:Option<String>,pub raw_payload_hash:[u8;32],pub normalizer_version:String,pub ingestion_instance:String,pub quality_score_ppm:u32,pub quality_flags:QualityFlags}
impl EventMetadata{pub fn validate(&self)->Result<(),EventError>{if self.schema_version==0||self.connection_epoch==0||self.receive_wall_timestamp<self.connection_started_at||self.raw_payload_hash==[0;32]||self.quality_score_ppm>1_000_000||self.normalizer_version.is_empty()||self.ingestion_instance.is_empty(){return Err(EventError::Metadata)}if self.source.kind()==SourceKind::Exchange&&self.venue.is_none(){return Err(EventError::Metadata)}if let Some(id)=&self.instrument_id{if self.venue.as_ref()!=Some(id.venue()){return Err(EventError::Metadata)}}Ok(())}}
#[derive(Clone,Copy,Debug,Eq,PartialEq,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum Side{Buy,Sell,Unknown}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct BookLevel{pub price:Price,pub quantity:Quantity,pub order_count:Option<u32>}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct Trade{pub trade_id:String,pub price:Price,pub quantity:Quantity,pub side:Side}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct TopOfBook{pub bid_price:Price,pub bid_quantity:Quantity,pub ask_price:Price,pub ask_quantity:Quantity}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct BookSnapshot{pub bids:Vec<BookLevel>,pub asks:Vec<BookLevel>,pub last_sequence:u64}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct BookDelta{pub bids:Vec<BookLevel>,pub asks:Vec<BookLevel>,pub first_sequence:u64,pub last_sequence:u64}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct Funding{pub current_rate:Rate,pub predicted_rate:Option<Rate>,pub next_funding_at:Option<UnixNanos>}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct OpenInterest{pub contracts:Quantity,pub quote_notional:Option<Notional>}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct Liquidation{pub side:Side,pub price:Price,pub quantity:Quantity,pub completeness:String,pub window_millis:Option<u32>}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct MarkIndex{pub mark_price:Price,pub index_price:Price}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct OptionTicker{pub mark_iv:Rate,pub bid_iv:Option<Rate>,pub ask_iv:Option<Rate>,pub delta:Option<Rate>,pub gamma:Option<Rate>,pub open_interest:Quantity}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct ChainBlock{pub chain:String,pub height:u64,pub hash:String,pub parent_hash:String,pub block_time:UnixNanos}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]#[serde(tag="kind",content="value",rename_all="snake_case")]pub enum EventPayload{Trade(Trade),TopOfBook(TopOfBook),BookSnapshot(BookSnapshot),BookDelta(BookDelta),InstrumentDefinition(InstrumentDefinition),Funding(Funding),OpenInterest(OpenInterest),Liquidation(Liquidation),MarkIndex(MarkIndex),OptionTicker(OptionTicker),ChainBlock(ChainBlock),StructuredEvent{event_type:String,assets:Vec<String>,source_reference:String},DataQuality{code:String,detail:String}}
impl EventPayload{fn validate(&self,m:&EventMetadata)->Result<(),EventError>{m.validate()?;let instrument=matches!(self,Self::Trade(_)|Self::TopOfBook(_)|Self::BookSnapshot(_)|Self::BookDelta(_)|Self::InstrumentDefinition(_)|Self::Funding(_)|Self::OpenInterest(_)|Self::Liquidation(_)|Self::MarkIndex(_)|Self::OptionTicker(_));if instrument&&(m.instrument_id.is_none()||m.venue.is_none()){return Err(EventError::Metadata)}match self{Self::Trade(v)if v.trade_id.is_empty()||v.quantity.value().is_zero()=>Err(EventError::Payload),Self::TopOfBook(v)if v.bid_price>=v.ask_price=>Err(EventError::Payload),Self::BookSnapshot(v)=>{book(&v.bids,&v.asks,false)?;if m.snapshot_kind!=SnapshotKind::Snapshot||m.sequence_number!=Some(v.last_sequence){return Err(EventError::SequenceMismatch)}Ok(())},Self::BookDelta(v)=>{book(&v.bids,&v.asks,true)?;if v.first_sequence>v.last_sequence||m.snapshot_kind!=SnapshotKind::Delta||m.sequence_number!=Some(v.last_sequence){return Err(EventError::SequenceMismatch)}Ok(())},Self::InstrumentDefinition(v)if m.instrument_id.as_ref()!=Some(v.id())=>Err(EventError::Metadata),Self::Liquidation(v)if v.quantity.value().is_zero()=>Err(EventError::Payload),Self::OptionTicker(v)if v.mark_iv.value().is_negative()||v.bid_iv.zip(v.ask_iv).is_some_and(|(a,b)|a>b)=>Err(EventError::Payload),Self::ChainBlock(v)if v.chain.is_empty()||v.hash.is_empty()=>Err(EventError::Payload),Self::StructuredEvent{assets,source_reference,..}if assets.is_empty()||source_reference.is_empty()=>Err(EventError::Payload),Self::DataQuality{code,detail}if code.is_empty()||detail.is_empty()=>Err(EventError::Payload),_=>Ok(())}}}
#[derive(Clone,Copy,Debug,Eq,Hash,PartialEq,Serialize,Deserialize)]#[serde(transparent)]pub struct EventId([u8;32]);impl std::fmt::Display for EventId{fn fmt(&self,f:&mut std::fmt::Formatter<'_>)->std::fmt::Result{f.write_str(&hex::encode(self.0))}}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct EventEnvelope{id:EventId,metadata:EventMetadata,payload:EventPayload}
impl EventEnvelope{pub fn new(metadata:EventMetadata,payload:EventPayload)->Result<Self,EventError>{payload.validate(&metadata)?;let id=calculate_id(&metadata,&payload)?;Ok(Self{id,metadata,payload})}pub const fn id(&self)->EventId{self.id}pub fn metadata(&self)->&EventMetadata{&self.metadata}pub fn payload(&self)->&EventPayload{&self.payload}pub fn verify(&self)->Result<(),EventError>{if calculate_id(&self.metadata,&self.payload)?==self.id{Ok(())}else{Err(EventError::IdentityMismatch)}}}
fn calculate_id(m:&EventMetadata,p:&EventPayload)->Result<EventId,EventError>{let mut bytes=Vec::new();bytes.extend_from_slice(EVENT_DOMAIN);put(&mut bytes,&serde_json::to_vec(m).map_err(|_|EventError::Payload)?)?;put(&mut bytes,&canonical_payload(p)? )?;Ok(EventId(*blake3::hash(&bytes).as_bytes()))}
fn canonical_payload(p:&EventPayload)->Result<Vec<u8>,EventError>{let mut b=Vec::new();match p{EventPayload::Trade(v)=>{s(&mut b,&v.trade_id);d(&mut b,v.price.value());d(&mut b,v.quantity.value());b.push(v.side as u8)},EventPayload::TopOfBook(v)=>for x in[v.bid_price.value(),v.bid_quantity.value(),v.ask_price.value(),v.ask_quantity.value()]{d(&mut b,x)},EventPayload::BookSnapshot(v)=>{levels(&mut b,&v.bids);levels(&mut b,&v.asks);b.extend_from_slice(&v.last_sequence.to_be_bytes())},EventPayload::BookDelta(v)=>{levels(&mut b,&v.bids);levels(&mut b,&v.asks);b.extend_from_slice(&v.first_sequence.to_be_bytes());b.extend_from_slice(&v.last_sequence.to_be_bytes())},EventPayload::InstrumentDefinition(v)=>s(&mut b,&v.id().to_string()),EventPayload::Funding(v)=>d(&mut b,v.current_rate.value()),EventPayload::OpenInterest(v)=>d(&mut b,v.contracts.value()),EventPayload::Liquidation(v)=>{d(&mut b,v.price.value());d(&mut b,v.quantity.value());s(&mut b,&v.completeness)},EventPayload::MarkIndex(v)=>{d(&mut b,v.mark_price.value());d(&mut b,v.index_price.value())},EventPayload::OptionTicker(v)=>d(&mut b,v.mark_iv.value()),EventPayload::ChainBlock(v)=>{s(&mut b,&v.chain);b.extend_from_slice(&v.height.to_be_bytes());s(&mut b,&v.hash);s(&mut b,&v.parent_hash)},EventPayload::StructuredEvent{event_type,assets,source_reference}=>{s(&mut b,event_type);for a in assets{s(&mut b,a)}s(&mut b,source_reference)},EventPayload::DataQuality{code,detail}=>{s(&mut b,code);s(&mut b,detail)}}Ok(b)}
fn put(b:&mut Vec<u8>,v:&[u8])->Result<(),EventError>{let n=u32::try_from(v.len()).map_err(|_|EventError::Payload)?;b.extend_from_slice(&n.to_be_bytes());b.extend_from_slice(v);Ok(())}fn s(b:&mut Vec<u8>,v:&str){b.extend_from_slice(&(v.len()as u32).to_be_bytes());b.extend_from_slice(v.as_bytes())}fn d(b:&mut Vec<u8>,v:FixedDecimal){s(b,&v.to_string())}fn levels(b:&mut Vec<u8>,v:&[BookLevel]){b.extend_from_slice(&(v.len()as u32).to_be_bytes());for l in v{d(b,l.price.value());d(b,l.quantity.value())}}
fn book(bids:&[BookLevel],asks:&[BookLevel],allow_zero:bool)->Result<(),EventError>{if bids.len()+asks.len()>MAX_LEVELS||(!allow_zero&&bids.iter().chain(asks).any(|l|l.quantity.value().is_zero()))||!bids.windows(2).all(|w|w[0].price>w[1].price)||!asks.windows(2).all(|w|w[0].price<w[1].price)||bids.first().zip(asks.first()).is_some_and(|(b,a)|b.price>=a.price){Err(EventError::Payload)}else{Ok(())}}
