//! Checked fixed-point values for authoritative monetary boundaries.
use serde::{Deserialize,Deserializer,Serialize,Serializer,de::Error as _};
use std::{cmp::Ordering,fmt,hash::{Hash,Hasher},str::FromStr};
use thiserror::Error;
pub const MAX_SCALE:u32=38;pub const MIN_SUPPORTED_I128:i128=i128::MIN;
#[derive(Clone,Debug,Eq,Error,PartialEq)]
pub enum DecimalError{#[error("invalid decimal syntax")]InvalidSyntax,#[error("scale too large")]ScaleTooLarge,#[error("arithmetic overflow")]Overflow,#[error("precision loss")]PrecisionLoss,#[error("division by zero")]DivisionByZero,#[error("non-positive {0}")]NonPositive(&'static str),#[error("negative {0}")]Negative(&'static str)}
#[derive(Clone,Copy,Debug)]pub struct FixedDecimal{mantissa:i128,scale:u32}
impl FixedDecimal{
pub fn new(mantissa:i128,scale:u32)->Result<Self,DecimalError>{if scale>MAX_SCALE{return Err(DecimalError::ScaleTooLarge)}Ok(Self{mantissa,scale}.canonicalized())}
pub fn parse(input:&str)->Result<Self,DecimalError>{if input.is_empty()||input.trim()!=input||input.starts_with('+'){return Err(DecimalError::InvalidSyntax)}
let(negative,body)=input.strip_prefix('-').map_or((false,input),|v|(true,v));let(whole,fraction)=match body.split_once('.') {Some((a,b))if !a.is_empty()&&!b.is_empty()=>(a,b),Some(_)=>return Err(DecimalError::InvalidSyntax),None=>(body,"")};
if whole.is_empty()||!whole.bytes().all(|b|b.is_ascii_digit())||!fraction.bytes().all(|b|b.is_ascii_digit()){return Err(DecimalError::InvalidSyntax)}
let scale=u32::try_from(fraction.len()).map_err(|_|DecimalError::Overflow)?;if scale>MAX_SCALE{return Err(DecimalError::ScaleTooLarge)}
let magnitude=format!("{whole}{fraction}").parse::<u128>().map_err(|_|DecimalError::Overflow)?;Self::new(signed(magnitude,negative)?,scale)}
pub const fn mantissa(self)->i128{self.mantissa}pub const fn scale(self)->u32{self.scale}pub const fn is_zero(self)->bool{self.mantissa==0}pub const fn is_positive(self)->bool{self.mantissa>0}pub const fn is_negative(self)->bool{self.mantissa<0}
pub fn canonicalized(mut self)->Self{if self.mantissa==0{self.scale=0;return self}while self.scale>0&&self.mantissa%10==0{self.mantissa/=10;self.scale-=1}self}
pub fn rescale_exact(self,target:u32)->Result<Self,DecimalError>{if target>MAX_SCALE{return Err(DecimalError::ScaleTooLarge)}match target.cmp(&self.scale){Ordering::Equal=>Ok(self),Ordering::Greater=>Self::new(self.mantissa.checked_mul(pow10(target-self.scale)?).ok_or(DecimalError::Overflow)?,target),Ordering::Less=>{let factor=pow10(self.scale-target)?;if self.mantissa%factor!=0{return Err(DecimalError::PrecisionLoss)}Self::new(self.mantissa/factor,target)}}}
pub fn checked_add(self,rhs:Self)->Result<Self,DecimalError>{decimal_op(self,rhs,false)}pub fn checked_sub(self,rhs:Self)->Result<Self,DecimalError>{decimal_op(self,rhs,true)}
pub fn checked_mul(self,rhs:Self)->Result<Self,DecimalError>{let a=self.canonicalized();let b=rhs.canonicalized();if a.is_zero()||b.is_zero(){return Self::new(0,0)}let mut scale=a.scale.checked_add(b.scale).ok_or(DecimalError::Overflow)?;
let mut digits=multiply_digits(&a.mantissa.unsigned_abs().to_string(),&b.mantissa.unsigned_abs().to_string());while scale>0&&digits.ends_with('0'){digits.pop();scale-=1}if scale>MAX_SCALE{return Err(DecimalError::ScaleTooLarge)}
let m=digits.parse::<u128>().map_err(|_|DecimalError::Overflow)?;Self::new(signed(m,a.is_negative()^b.is_negative())?,scale)}
pub fn checked_div_exact(self,rhs:Self,target:u32)->Result<Self,DecimalError>{let a=self.canonicalized();let b=rhs.canonicalized();if b.is_zero(){return Err(DecimalError::DivisionByZero)}if target>MAX_SCALE{return Err(DecimalError::ScaleTooLarge)}
if a.is_zero(){return Self::new(0,0)}let neg=a.is_negative()^b.is_negative();let mut n=a.mantissa.unsigned_abs();let mut d=b.mantissa.unsigned_abs();let g=gcd(n,d);n/=g;d/=g;let exponent=i64::from(target)+i64::from(b.scale)-i64::from(a.scale);
let magnitude=if exponent>=0{let p=u32::try_from(exponent).map_err(|_|DecimalError::Overflow)?;let(t,r)=remove_factor(d,2);let(f,r)=remove_factor(r,5);if r!=1||t>p||f>p{return Err(DecimalError::PrecisionLoss)}mul_power(mul_power(n,2,p-t)?,5,p-f)?}
else{if d!=1{return Err(DecimalError::PrecisionLoss)}for _ in 0..u32::try_from(-exponent).map_err(|_|DecimalError::Overflow)?{if n%10!=0{return Err(DecimalError::PrecisionLoss)}n/=10}n};Self::new(signed(magnitude,neg)?,target)}
pub fn checked_neg(self)->Result<Self,DecimalError>{Self::new(self.mantissa.checked_neg().ok_or(DecimalError::Overflow)?,self.scale)}
pub fn to_f64_lossy_for_analysis(self)->f64{self.mantissa as f64/10_f64.powi(self.scale as i32)}
}
impl FromStr for FixedDecimal{type Err=DecimalError;fn from_str(v:&str)->Result<Self,Self::Err>{Self::parse(v)}}
impl fmt::Display for FixedDecimal{fn fmt(&self,f:&mut fmt::Formatter<'_>)->fmt::Result{let v=self.canonicalized();let neg=v.mantissa<0;let mut d=v.mantissa.unsigned_abs().to_string();if v.scale==0{if neg{f.write_str("-")?}return f.write_str(&d)}let s=v.scale as usize;if d.len()<=s{d=format!("{}{}", "0".repeat(s+1-d.len()),d)}let i=d.len()-s;if neg{f.write_str("-")?}write!(f,"{}.{}",&d[..i],&d[i..])}}
impl PartialEq for FixedDecimal{fn eq(&self,o:&Self)->bool{let a=self.canonicalized();let b=o.canonicalized();a.mantissa==b.mantissa&&a.scale==b.scale}}impl Eq for FixedDecimal{}
impl Hash for FixedDecimal{fn hash<H:Hasher>(&self,h:&mut H){let v=self.canonicalized();v.mantissa.hash(h);v.scale.hash(h)}}
impl Ord for FixedDecimal{fn cmp(&self,o:&Self)->Ordering{let a=self.canonicalized();let b=o.canonicalized();let sign=a.mantissa.signum().cmp(&b.mantissa.signum());if sign!=Ordering::Equal{return sign}if a.is_zero(){return Ordering::Equal}let ordering=compare_scaled(a.mantissa.unsigned_abs(),a.scale,b.mantissa.unsigned_abs(),b.scale);if a.is_negative(){ordering.reverse()}else{ordering}}}
impl PartialOrd for FixedDecimal{fn partial_cmp(&self,o:&Self)->Option<Ordering>{Some(self.cmp(o))}}
impl Serialize for FixedDecimal{fn serialize<S:Serializer>(&self,s:S)->Result<S::Ok,S::Error>{s.serialize_str(&self.to_string())}}
impl<'de>Deserialize<'de> for FixedDecimal{fn deserialize<D:Deserializer<'de>>(d:D)->Result<Self,D::Error>{Self::parse(&String::deserialize(d)?).map_err(D::Error::custom)}}
macro_rules! wrapper{($name:ident,$predicate:expr,$error:expr)=>{#[derive(Clone,Copy,Debug,Eq,Hash,Ord,PartialEq,PartialOrd)]pub struct $name(FixedDecimal);impl $name{pub fn new(v:FixedDecimal)->Result<Self,DecimalError>{if($predicate)(v){Ok(Self(v))}else{Err($error)}}pub const fn value(self)->FixedDecimal{self.0}}impl fmt::Display for $name{fn fmt(&self,f:&mut fmt::Formatter<'_>)->fmt::Result{self.0.fmt(f)}}impl Serialize for $name{fn serialize<S:Serializer>(&self,s:S)->Result<S::Ok,S::Error>{self.0.serialize(s)}}impl<'de>Deserialize<'de> for $name{fn deserialize<D:Deserializer<'de>>(d:D)->Result<Self,D::Error>{Self::new(FixedDecimal::deserialize(d)?).map_err(D::Error::custom)}}};}
wrapper!(Price,|v:FixedDecimal|v.is_positive(),DecimalError::NonPositive("price"));wrapper!(Quantity,|v:FixedDecimal|!v.is_negative(),DecimalError::Negative("quantity"));wrapper!(Notional,|v:FixedDecimal|!v.is_negative(),DecimalError::Negative("notional"));wrapper!(Rate,|_:FixedDecimal|true,DecimalError::InvalidSyntax);
fn signed(m:u128,n:bool)->Result<i128,DecimalError>{if n{if m==(i128::MAX as u128)+1{Ok(i128::MIN)}else{i128::try_from(m).map_err(|_|DecimalError::Overflow)?.checked_neg().ok_or(DecimalError::Overflow)}}else{i128::try_from(m).map_err(|_|DecimalError::Overflow)}}
fn pow10(p:u32)->Result<i128,DecimalError>{10_i128.checked_pow(p).ok_or(DecimalError::Overflow)}fn gcd(mut a:u128,mut b:u128)->u128{while b!=0{let r=a%b;a=b;b=r}a}
fn remove_factor(mut v:u128,f:u128)->(u32,u128){let mut c=0;while v%f==0{v/=f;c+=1}(c,v)}fn mul_power(mut v:u128,f:u128,p:u32)->Result<u128,DecimalError>{for _ in 0..p{v=v.checked_mul(f).ok_or(DecimalError::Overflow)?}Ok(v)}
fn compare_scaled(a:u128,as_:u32,b:u128,bs:u32)->Ordering{let mut x=a.to_string();let mut y=b.to_string();x.extend(std::iter::repeat_n('0',bs as usize));y.extend(std::iter::repeat_n('0',as_ as usize));x.len().cmp(&y.len()).then_with(||x.cmp(&y))}
fn decimal_op(a:FixedDecimal,b:FixedDecimal,subtract:bool)->Result<FixedDecimal,DecimalError>{let a=a.canonicalized();let b=b.canonicalized();let scale=a.scale.max(b.scale);let ad=scaled(a,scale);let bd=scaled(b,scale);let an=a.is_negative();let bn=b.is_negative()^subtract;let(negative,digits)=if an==bn{(an,add_digits(&ad,&bd))}else{match compare_digits(&ad,&bd){Ordering::Greater=>(an,sub_digits(&ad,&bd)),Ordering::Less=>(bn,sub_digits(&bd,&ad)),Ordering::Equal=>(false,"0".into())}};let m=digits.parse::<u128>().map_err(|_|DecimalError::Overflow)?;FixedDecimal::new(signed(m,negative)?,scale)}
fn scaled(v:FixedDecimal,s:u32)->String{format!("{}{}",v.mantissa.unsigned_abs(),"0".repeat((s-v.scale)as usize))}fn compare_digits(a:&str,b:&str)->Ordering{let a=a.trim_start_matches('0');let b=b.trim_start_matches('0');a.len().cmp(&b.len()).then_with(||a.cmp(b))}
fn add_digits(a:&str,b:&str)->String{let mut out=Vec::new();let mut x=a.bytes().rev();let mut y=b.bytes().rev();let mut c=0;loop{let p=x.next().map(|v|v-b'0');let q=y.next().map(|v|v-b'0');if p.is_none()&&q.is_none()&&c==0{break}let s=p.unwrap_or(0)+q.unwrap_or(0)+c;out.push(b'0'+s%10);c=s/10}out.reverse();String::from_utf8(out).unwrap_or_else(|_|"0".into())}
fn sub_digits(a:&str,b:&str)->String{let mut out=Vec::new();let mut y=b.bytes().rev();let mut borrow=0_i16;for x in a.bytes().rev(){let l=i16::from(x-b'0')-borrow;let r=i16::from(y.next().unwrap_or(b'0')-b'0');let(d,n)=if l<r{(l+10-r,1)}else{(l-r,0)};out.push(b'0'+u8::try_from(d).unwrap_or(0));borrow=n}while out.len()>1&&out.last()==Some(&b'0'){out.pop()}out.reverse();String::from_utf8(out).unwrap_or_else(|_|"0".into())}
fn multiply_digits(a:&str,b:&str)->String{let mut acc=vec![0_u16;a.len()+b.len()];for(i,x)in a.bytes().rev().enumerate(){for(j,y)in b.bytes().rev().enumerate(){acc[i+j]+=u16::from(x-b'0')*u16::from(y-b'0')}}for i in 0..acc.len()-1{let c=acc[i]/10;acc[i]%=10;acc[i+1]+=c}while acc.len()>1&&acc.last()==Some(&0){acc.pop()}acc.into_iter().rev().map(|v|char::from(b'0'+u8::try_from(v).unwrap_or(0))).collect()}
#[cfg(test)]mod tests{use super::*;#[test]fn exact(){assert_eq!(FixedDecimal::parse("1.2300").unwrap().to_string(),"1.23")}#[test]fn minimum_subtracted_from_itself(){let m=FixedDecimal::new(i128::MIN,0).unwrap();assert_eq!(m.checked_sub(m).unwrap(),FixedDecimal::new(0,0).unwrap())}}
