use fixed_decimal::{DecimalError,FixedDecimal,Notional,Price,Quantity};use serde::{Deserialize,Deserializer,Serialize,de::Error as _};use std::fmt;use thiserror::Error;use uuid::Uuid;
#[derive(Clone,Debug,Eq,Error,PartialEq)]pub enum DomainError{#[error("invalid identity field")]Invalid,#[error("generation zero")]GenerationZero,#[error("invalid address")]Address,#[error("identical base and quote")]IdenticalBaseQuote,#[error("invalid instrument")]Instrument,#[error(transparent)]Decimal(#[from]DecimalError)}
#[derive(Clone,Debug,Eq,Hash,PartialEq,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum AssetNamespace{Native,Fiat,Evm,Solana,Cosmos,Other(String)}
#[derive(Clone,Debug,Eq,Hash,PartialEq,Serialize)]pub struct AssetId{namespace:AssetNamespace,chain:String,address:String,symbol:String,generation:u32}
#[derive(Deserialize)]struct AssetWire{namespace:AssetNamespace,chain:String,address:String,symbol:String,generation:u32}
impl AssetId{pub fn new(namespace:AssetNamespace,chain:impl Into<String>,address:impl Into<String>,symbol:impl Into<String>,generation:u32)->Result<Self,DomainError>{let chain=chain.into();let mut address=address.into();let symbol=symbol.into();token(&chain,64,false)?;token(&symbol,32,true)?;if generation==0{return Err(DomainError::GenerationZero)}match namespace{AssetNamespace::Native|AssetNamespace::Fiat if !address.is_empty()=>return Err(DomainError::Address),AssetNamespace::Evm=>{if address.len()!=42||!address.starts_with("0x")||!address[2..].bytes().all(|b|b.is_ascii_hexdigit()){return Err(DomainError::Address)}address=address.to_ascii_lowercase()},AssetNamespace::Solana if !(32..=44).contains(&address.len())=>return Err(DomainError::Address),AssetNamespace::Cosmos if !address.contains('1')=>return Err(DomainError::Address),_=>{}}Ok(Self{namespace,chain,address,symbol,generation})}pub fn namespace(&self)->&AssetNamespace{&self.namespace}pub fn chain(&self)->&str{&self.chain}pub fn address(&self)->&str{&self.address}pub fn symbol(&self)->&str{&self.symbol}pub const fn generation(&self)->u32{self.generation}}
impl<'de>Deserialize<'de> for AssetId{fn deserialize<D:Deserializer<'de>>(d:D)->Result<Self,D::Error>{let w=AssetWire::deserialize(d)?;Self::new(w.namespace,w.chain,w.address,w.symbol,w.generation).map_err(D::Error::custom)}}
impl fmt::Display for AssetId{fn fmt(&self,f:&mut fmt::Formatter<'_>)->fmt::Result{write!(f,"{:?}:{}:{}:{}:{}",self.namespace,self.chain,self.address,self.symbol,self.generation)}}
macro_rules! id{($n:ident)=>{#[derive(Clone,Debug,Eq,Hash,Ord,PartialEq,PartialOrd,Serialize,Deserialize)]#[serde(try_from="String",into="String")]pub struct $n(String);impl $n{pub fn new(v:impl Into<String>)->Result<Self,DomainError>{let v=v.into();token(&v,128,false)?;Ok(Self(v))}pub fn as_str(&self)->&str{&self.0}}impl TryFrom<String> for $n{type Error=DomainError;fn try_from(v:String)->Result<Self,Self::Error>{Self::new(v)}}impl From<$n> for String{fn from(v:$n)->Self{v.0}}impl fmt::Display for $n{fn fmt(&self,f:&mut fmt::Formatter<'_>)->fmt::Result{f.write_str(&self.0)}}};}
id!(VenueId);id!(ModelPackageId);id!(ForecastId);id!(EvidenceBundleId);
#[derive(Clone,Copy,Debug,Eq,Hash,PartialEq,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum SourceKind{Exchange,Chain,Macro,News,Derived,System}
#[derive(Clone,Debug,Eq,Hash,PartialEq,Serialize,Deserialize)]pub struct SourceId{kind:SourceKind,name:String,generation:u32}
impl SourceId{pub fn new(kind:SourceKind,name:impl Into<String>,generation:u32)->Result<Self,DomainError>{let name=name.into();token(&name,96,false)?;if generation==0{return Err(DomainError::GenerationZero)}Ok(Self{kind,name,generation})}pub const fn kind(&self)->SourceKind{self.kind}pub fn name(&self)->&str{&self.name}pub const fn generation(&self)->u32{self.generation}}
#[derive(Clone,Copy,Debug,Eq,Hash,Ord,PartialEq,PartialOrd,Serialize,Deserialize)]#[serde(transparent)]pub struct UnixNanos(i64);impl UnixNanos{pub const fn new(v:i64)->Self{Self(v)}pub const fn value(self)->i64{self.0}}
#[derive(Clone,Debug,Eq,Hash,PartialEq,Serialize,Deserialize)]pub struct InstrumentId{venue:VenueId,venue_symbol:String,generation:u32}
impl InstrumentId{pub fn new(venue:VenueId,symbol:impl Into<String>,generation:u32)->Result<Self,DomainError>{let venue_symbol=symbol.into();if venue_symbol.is_empty()||venue_symbol.len()>96||generation==0{return Err(DomainError::Invalid)}Ok(Self{venue,venue_symbol,generation})}pub fn venue(&self)->&VenueId{&self.venue}pub fn venue_symbol(&self)->&str{&self.venue_symbol}pub const fn generation(&self)->u32{self.generation}}
impl fmt::Display for InstrumentId{fn fmt(&self,f:&mut fmt::Formatter<'_>)->fmt::Result{write!(f,"{}:{}:{}",self.venue,self.venue_symbol,self.generation)}}
#[derive(Clone,Copy,Debug,Eq,Hash,PartialEq,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum ProductType{Spot,Perpetual,Future,Option}
#[derive(Clone,Copy,Debug,Eq,Hash,PartialEq,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum ContractKind{None,Linear,Inverse}
#[derive(Clone,Copy,Debug,Eq,Hash,PartialEq,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum OptionSide{Call,Put}
#[derive(Clone,Copy,Debug,Eq,Hash,PartialEq,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum InstrumentStatus{Announced,Active,Suspended,Delisted}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct InstrumentDefinitionInput{pub id:InstrumentId,pub base_asset:AssetId,pub quote_asset:AssetId,pub settlement_asset:AssetId,pub product_type:ProductType,pub contract_kind:ContractKind,pub price_tick:Price,pub quantity_step:Quantity,pub contract_multiplier:FixedDecimal,pub expiry:Option<UnixNanos>,pub strike:Option<Price>,pub option_side:Option<OptionSide>,pub status:InstrumentStatus,pub listed_at:UnixNanos,pub delisted_at:Option<UnixNanos>}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct InstrumentDefinition{input:InstrumentDefinitionInput}
impl InstrumentDefinition{pub fn new(input:InstrumentDefinitionInput)->Result<Self,DomainError>{if input.base_asset==input.quote_asset{return Err(DomainError::IdenticalBaseQuote)}if input.quantity_step.value().is_zero()||!input.contract_multiplier.is_positive(){return Err(DomainError::Instrument)}match input.contract_kind{ContractKind::None|ContractKind::Linear if input.settlement_asset!=input.quote_asset=>return Err(DomainError::Instrument),ContractKind::Inverse if input.settlement_asset!=input.base_asset=>return Err(DomainError::Instrument),_=>{}}match input.product_type{ProductType::Spot if input.contract_kind!=ContractKind::None||input.expiry.is_some()||input.strike.is_some()=>return Err(DomainError::Instrument),ProductType::Perpetual if input.contract_kind==ContractKind::None||input.expiry.is_some()=>return Err(DomainError::Instrument),ProductType::Future if input.contract_kind==ContractKind::None||input.expiry.is_none()=>return Err(DomainError::Instrument),ProductType::Option if input.contract_kind==ContractKind::None||input.expiry.is_none()||input.strike.is_none()||input.option_side.is_none()=>return Err(DomainError::Instrument),_=>{}}Ok(Self{input})}pub fn id(&self)->&InstrumentId{&self.input.id}pub fn base_asset(&self)->&AssetId{&self.input.base_asset}pub fn quote_asset(&self)->&AssetId{&self.input.quote_asset}pub fn settlement_asset(&self)->&AssetId{&self.input.settlement_asset}pub const fn product_type(&self)->ProductType{self.input.product_type}pub const fn contract_kind(&self)->ContractKind{self.input.contract_kind}pub const fn price_tick(&self)->Price{self.input.price_tick}pub const fn quantity_step(&self)->Quantity{self.input.quantity_step}pub const fn contract_multiplier(&self)->FixedDecimal{self.input.contract_multiplier}pub fn quote_notional(&self,contracts:Quantity,price:Price)->Result<Notional,DomainError>{let v=match self.input.contract_kind{ContractKind::Inverse=>contracts.value().checked_mul(self.input.contract_multiplier)?,_=>contracts.value().checked_mul(self.input.contract_multiplier)?.checked_mul(price.value())?};Ok(Notional::new(v)?)}}
#[derive(Clone,Copy,Debug,Eq,Hash,PartialEq,Serialize,Deserialize)]pub struct RunId(Uuid);impl RunId{pub fn now_v7()->Self{Self(Uuid::now_v7())}}
fn token(v:&str,max:usize,upper:bool)->Result<(),DomainError>{if v.is_empty()||v.len()>max||!v.is_ascii(){return Err(DomainError::Invalid)}let ok=v.bytes().all(|b|if upper{b.is_ascii_uppercase()||b.is_ascii_digit()||matches!(b,b'-'|b'_'|b'.')}else{b.is_ascii_lowercase()||b.is_ascii_digit()||matches!(b,b'-'|b'_'|b'.'|b':'|b'@')});if ok{Ok(())}else{Err(DomainError::Invalid)}}
