[package]
name = "volatility"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
autotests = false

[dependencies]
thiserror.workspace = true

[[test]]
name = "reference_measures"
path = "tests/reference_measures.rs"

[lints]
workspace = true
