use numerics::{NumericalError,real_cubic_roots};use rand::{Rng,SeedableRng,rngs::StdRng};use serde::{Deserialize,Serialize};use thiserror::Error;
#[derive(Clone,Copy,Debug,PartialEq,Serialize,Deserialize)]pub struct ControlPoint{pub alpha:f64,pub beta:f64}impl ControlPoint{pub fn discriminant(self)->f64{4.0*self.beta.powi(3)-27.0*self.alpha.powi(2)}pub fn inside_cusp(self)->bool{self.beta>0.0&&self.discriminant()>0.0}}
#[derive(Clone,Copy,Debug,Eq,PartialEq,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum Branch{Bear,Unstable,Bull,Single,Ambiguous}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]pub struct Equilibrium{pub state:f64,pub potential:f64,pub curvature:f64,pub stable:bool,pub branch:Branch}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]pub struct CuspState{pub controls:ControlPoint,pub cusp_probability:f64,pub fold_margin:f64,pub equilibria:Vec<Equilibrium>,pub current_branch:Branch,pub barrier_height:Option<f64>,pub restoring_force:Option<f64>,pub as_known_at_ns:i64,pub model_id:String}
pub fn potential(z:f64,c:ControlPoint)->f64{0.25*z.powi(4)-0.5*c.beta*z*z-c.alpha*z}pub fn gradient(z:f64,c:ControlPoint)->f64{z.powi(3)-c.beta*z-c.alpha}pub fn curvature(z:f64,c:ControlPoint)->f64{3.0*z*z-c.beta}
pub fn equilibria(c:ControlPoint,tol:f64)->Result<Vec<Equilibrium>,CuspError>{let roots=real_cubic_roots(-c.beta,-c.alpha,tol)?;Ok(roots.iter().enumerate().map(|(i,r)|{let k=curvature(r.value,c);Equilibrium{state:r.value,potential:potential(r.value,c),curvature:k,stable:k>tol,branch:if roots.len()==3{match i{0=>Branch::Bear,1=>Branch::Unstable,_=>Branch::Bull}}else{Branch::Single}}}).collect())}
pub fn classify(c:ControlPoint,current:f64,samples:&[ControlPoint],at:i64)->Result<CuspState,CuspError>{if samples.is_empty(){return Err(CuspError::Input)}let eq=equilibria(c,1e-10)?;let probability=samples.iter().filter(|v|v.inside_cusp()).count()as f64/samples.len()as f64;let stable=eq.iter().filter(|e|e.stable).min_by(|a,b|(a.state-current).abs().total_cmp(&(b.state-current).abs()));let unstable=eq.iter().find(|e|!e.stable);Ok(CuspState{controls:c,cusp_probability:probability,fold_margin:c.discriminant(),current_branch:stable.map(|e|e.branch).unwrap_or(Branch::Ambiguous),barrier_height:stable.zip(unstable).map(|(s,u)|(u.potential-s.potential).max(0.0)),restoring_force:stable.map(|e|e.curvature),equilibria:eq,as_known_at_ns:at,model_id:"stochastic-cusp-v1".into()})}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]pub struct ControlModel{pub alpha_intercept:f64,pub beta_intercept:f64,pub alpha_weights:Vec<f64>,pub beta_weights:Vec<f64>,pub alpha_scale:f64,pub beta_scale:f64}
impl ControlModel{pub fn controls(&self,x:&[f64])->Result<ControlPoint,CuspError>{if x.len()!=self.alpha_weights.len()||x.len()!=self.beta_weights.len()||x.is_empty()||x.iter().any(|v|!v.is_finite())||self.alpha_scale<=0.0||self.beta_scale<=0.0{return Err(CuspError::Input)}Ok(ControlPoint{alpha:self.alpha_intercept+self.alpha_weights.iter().zip(x).map(|(a,b)|a*b).sum::<f64>(),beta:self.beta_intercept+self.beta_weights.iter().zip(x).map(|(a,b)|a*b).sum::<f64>()})}pub fn posterior(&self,x:&[f64],n:usize,seed:u64)->Result<Vec<ControlPoint>,CuspError>{if n==0||n>100_000{return Err(CuspError::Input)}let mean=self.controls(x)?;let mut rng=StdRng::seed_from_u64(seed);Ok((0..n).map(|_|{let normal=|r:&mut StdRng|{let a=r.gen::<f64>().clamp(f64::MIN_POSITIVE,1.0);let b=r.gen::<f64>();(-2.0*a.ln()).sqrt()*(std::f64::consts::TAU*b).cos()};ControlPoint{alpha:mean.alpha+normal(&mut rng)*self.alpha_scale,beta:mean.beta+normal(&mut rng)*self.beta_scale}}).collect())}}
#[derive(Debug,Error)]pub enum CuspError{#[error("invalid cusp input")]Input,#[error(transparent)]Numerical(#[from]NumericalError)}
