pub const SECURITY_REVIEW_FIELD:&str="security_review_id";
use serde::{Deserialize,Serialize};use thiserror::Error;use uuid::Uuid;
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]pub struct FoldEvidence{pub fold_id:String,pub positives:u64,pub observations:u64,pub brier_skill:f64,pub log_loss_improvement:f64,pub calibration_slope:f64,pub calibration_intercept:f64,pub event_regime:String}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]pub struct MonitoringSummary{pub positives:u64,pub observations:u64,pub population_stability_index:f64,pub subgroup_coverage_ok:bool}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]pub struct PromotionEvidence{pub package_id:String,pub candidate_version:String,pub baseline_package_id:String,pub folds:Vec<FoldEvidence>,pub shadow:MonitoringSummary,pub security_review_id:String,pub replay_report_hash:String,pub performance_report_hash:String,pub generated_at_ns:i64}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]pub struct PromotionPolicy{pub minimum_walkforward_positives:u64,pub minimum_shadow_positives:u64,pub minimum_regimes:usize,pub minimum_positive_fold_fraction:f64,pub minimum_brier_skill:f64,pub calibration_slope_min:f64,pub calibration_slope_max:f64,pub calibration_intercept_abs_max:f64,pub maximum_psi:f64,pub require_security_review:bool}
impl Default for PromotionPolicy{fn default()->Self{Self{minimum_walkforward_positives:50,minimum_shadow_positives:20,minimum_regimes:3,minimum_positive_fold_fraction:0.70,minimum_brier_skill:0.0,calibration_slope_min:0.80,calibration_slope_max:1.20,calibration_intercept_abs_max:0.05,maximum_psi:0.25,require_security_review:true}}}
#[derive(Clone,Copy,Debug,Eq,PartialEq,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum Decision{ApproveShadow,ApproveProduction,Reject,Revoke,Rollback}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct PromotionDecision{pub decision_id:Uuid,pub package_id:String,pub decision:Decision,pub decided_at_ns:i64,pub approver:String,pub reasons:Vec<String>,pub evidence_hash:String,pub replaces_package_id:Option<String>}
pub fn evaluate(policy:&PromotionPolicy,e:&PromotionEvidence,approver:&str,at:i64)->Result<PromotionDecision,PromotionError>{if e.package_id.is_empty()||e.folds.is_empty()||approver.is_empty(){return Err(PromotionError::Input)}let mut reasons=Vec::new();if e.folds.iter().map(|f|f.positives).sum::<u64>()<policy.minimum_walkforward_positives{reasons.push("insufficient_walkforward_positives".into())}if e.shadow.positives<policy.minimum_shadow_positives{reasons.push("insufficient_shadow_positives".into())}if e.folds.iter().map(|f|f.event_regime.as_str()).collect::<std::collections::BTreeSet<_>>().len()<policy.minimum_regimes{reasons.push("insufficient_regime_coverage".into())}let positive=e.folds.iter().filter(|f|f.brier_skill>policy.minimum_brier_skill).count()as f64/e.folds.len()as f64;if positive<policy.minimum_positive_fold_fraction{reasons.push("unstable_fold_improvement".into())}if e.folds.iter().any(|f|f.calibration_slope<policy.calibration_slope_min||f.calibration_slope>policy.calibration_slope_max||f.calibration_intercept.abs()>policy.calibration_intercept_abs_max){reasons.push("calibration_gate".into())}if e.shadow.population_stability_index>policy.maximum_psi||!e.shadow.subgroup_coverage_ok{reasons.push("shadow_gate".into())}if policy.require_security_review&&e.security_review_id.is_empty(){reasons.push("security_review_missing".into())}let decision=if reasons.is_empty(){Decision::ApproveProduction}else{Decision::Reject};let hash=blake3::hash(&serde_json::to_vec(e)?).to_hex().to_string();Ok(PromotionDecision{decision_id:Uuid::now_v7(),package_id:e.package_id.clone(),decision,decided_at_ns:at,approver:approver.into(),reasons,evidence_hash:hash,replaces_package_id:Some(e.baseline_package_id.clone())})}
#[derive(Debug,Error)]pub enum PromotionError{#[error("input")]Input,#[error(transparent)]Json(#[from]serde_json::Error)}
