use schemars::JsonSchema;use serde::{Deserialize,Serialize};use std::{collections::BTreeSet,net::SocketAddr,path::PathBuf};use thiserror::Error;use url::Url;
#[derive(Clone,Debug,Eq,PartialEq,Serialize,JsonSchema)]pub struct KeychainReference{service:String,account:String}impl KeychainReference{pub fn parse(v:&str)->Result<Self,ConfigError>{let body=v.strip_prefix("keychain://").ok_or(ConfigError::Credential)?;let(s,a)=body.split_once('/').ok_or(ConfigError::Credential)?;if a.contains('/')||![s,a].iter().all(|x|!x.is_empty()&&x.len()<=128&&x.bytes().all(|b|b.is_ascii_alphanumeric()||matches!(b,b'.'|b'_'|b'-'|b'@'))){return Err(ConfigError::Credential)}Ok(Self{service:s.into(),account:a.into()})}}impl<'de>Deserialize<'de> for KeychainReference{fn deserialize<D:serde::Deserializer<'de>>(d:D)->Result<Self,D::Error>{use serde::de::Error as _;Self::parse(&String::deserialize(d)?).map_err(D::Error::custom)}}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize,JsonSchema)]#[serde(deny_unknown_fields)]pub struct AppConfig{pub schema_version:u32,pub data_root:PathBuf,pub models_root:PathBuf,pub log_root:PathBuf,pub bind_address:String,pub session_secret_fd:u32,pub maximum_request_bytes:usize,pub maximum_concurrent_requests:usize,pub maximum_stream_buffer:usize,pub request_timeout_seconds:u64,pub remote_export:bool,pub allow_experimental:bool,pub minimum_quality_ppm:u32,pub connectors:Vec<ConnectorConfig>}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize,JsonSchema)]#[serde(deny_unknown_fields)]pub struct ConnectorConfig{pub id:String,pub enabled:bool,pub websocket_url:Option<String>,pub rest_url:Option<String>,#[schemars(with="Option<String>")]pub credential_ref:Option<KeychainReference>,pub channel_capacity:usize}
#[derive(Clone,Debug,Default)]pub struct Overrides{pub data_root:Option<PathBuf>,pub bind_address:Option<String>,pub allow_experimental:Option<bool>,pub session_secret_fd:Option<u32>}
#[derive(Clone,Debug)]pub struct EffectiveConfig{pub config:AppConfig,pub fingerprint:String,pub sources:Vec<String>}
impl AppConfig{pub fn validate(&mut self)->Result<(),ConfigError>{if self.schema_version!=1||self.data_root.as_os_str().is_empty()||self.models_root.as_os_str().is_empty()||self.log_root.as_os_str().is_empty()||self.session_secret_fd<3||self.maximum_request_bytes==0||self.maximum_concurrent_requests==0||self.maximum_stream_buffer==0||self.request_timeout_seconds==0||self.remote_export||self.minimum_quality_ppm>1_000_000{return Err(ConfigError::Invalid)}let address:SocketAddr=self.bind_address.parse()?;if !address.ip().is_loopback(){return Err(ConfigError::NonLoopback)}self.connectors.sort_by(|a,b|a.id.cmp(&b.id));let mut ids=BTreeSet::new();for c in &self.connectors{if !ids.insert(&c.id)||c.id.is_empty()||c.channel_capacity==0||c.enabled&&c.websocket_url.is_none(){return Err(ConfigError::Connector)}if let Some(v)=&c.websocket_url{endpoint(v,&["wss"])?}if let Some(v)=&c.rest_url{endpoint(v,&["https"])?}}Ok(())}}
pub fn load(default_text:&str,default_source:&str,user:Option<(&str,&str)>,overrides:Overrides)->Result<EffectiveConfig,ConfigError>{let mut merged:toml::Value=toml::from_str(default_text).map_err(|_|ConfigError::Parse)?;let mut sources=vec![default_source.into()];if let Some((text,source))=user{merge(&mut merged,toml::from_str(text).map_err(|_|ConfigError::Parse)?);sources.push(source.into())}let mut config:AppConfig=toml::from_str(&toml::to_string(&merged).map_err(|_|ConfigError::Parse)?).map_err(|_|ConfigError::Parse)?;if let Some(v)=overrides.data_root{config.data_root=v}if let Some(v)=overrides.bind_address{config.bind_address=v}if let Some(v)=overrides.allow_experimental{config.allow_experimental=v}if let Some(v)=overrides.session_secret_fd{config.session_secret_fd=v}config.validate()?;Ok(EffectiveConfig{fingerprint:blake3::hash(&serde_json::to_vec(&config)?).to_hex().to_string(),config,sources})}
fn merge(a:&mut toml::Value,b:toml::Value){match(a,b){(toml::Value::Table(x),toml::Value::Table(y))=>for(k,v)in y{if let Some(e)=x.get_mut(&k){merge(e,v)}else{x.insert(k,v);}},(x,y)=>*x=y}}fn endpoint(v:&str,schemes:&[&str])->Result<(),ConfigError>{let u=Url::parse(v).map_err(|_|ConfigError::Endpoint)?;if !schemes.contains(&u.scheme())||!u.username().is_empty()||u.password().is_some()||u.host_str().is_none(){Err(ConfigError::Endpoint)}else{Ok(())}}
#[derive(Debug,Error)]pub enum ConfigError{#[error("invalid config")]Invalid,#[error("parse")]Parse,#[error("credential")]Credential,#[error("non-loopback")]NonLoopback,#[error("connector")]Connector,#[error("endpoint")]Endpoint,#[error(transparent)]Address(#[from]std::net::AddrParseError),#[error(transparent)]Json(#[from]serde_json::Error)}
