use serde::{Deserialize,Serialize};use sha2::{Digest,Sha256};use std::{fs,path::{Component,Path}};use thiserror::Error;use uuid::Uuid;
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct FileEntry{pub path:String,pub bytes:u64,pub sha256:String,pub blake3:String,pub executable:bool}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct ReleaseManifest{pub schema_version:u32,pub release_id:Uuid,pub version:String,pub channel:String,pub commit:String,pub created_at_ns:i64,pub files:Vec<FileEntry>,pub manifest_sha256:String}
#[derive(Clone,Copy,Debug,Eq,PartialEq,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum GateStatus{Passed,Failed,Pending,NotApplicable}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct GateEvidence{pub gate:String,pub status:GateStatus,pub command:String,pub artifact_hash:Option<String>,pub reason:Option<String>}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct ReleaseEvidence{pub schema_version:u32,pub version:String,pub channel:String,pub commit:String,pub generated_at_ns:i64,pub gates:Vec<GateEvidence>,pub stable_eligible:bool,pub evidence_hash:String}
pub fn build_manifest(root:&Path,version:&str,channel:&str,commit:&str,at:i64)->Result<ReleaseManifest,ReleaseError>{if version.is_empty()||channel.is_empty()||commit.len()<7{return Err(ReleaseError::Input)}let mut files=Vec::new();walk(root,root,&mut files)?;files.sort_by(|a,b|a.path.cmp(&b.path));if files.is_empty()||files.windows(2).any(|w|w[0].path>=w[1].path){return Err(ReleaseError::Manifest)}let canonical=serde_json::to_vec(&(1_u32,version,channel,commit,at,&files))?;Ok(ReleaseManifest{schema_version:1,release_id:Uuid::now_v7(),version:version.into(),channel:channel.into(),commit:commit.into(),created_at_ns:at,files,manifest_sha256:hex::encode(Sha256::digest(canonical))})}
pub fn build_evidence(version:&str,channel:&str,commit:&str,at:i64,gates:Vec<GateEvidence>)->Result<ReleaseEvidence,ReleaseError>{if gates.is_empty(){return Err(ReleaseError::Evidence)}let stable_eligible=channel!="stable"||gates.iter().all(|g|matches!(g.status,GateStatus::Passed|GateStatus::NotApplicable));let b=serde_json::to_vec(&(version,channel,commit,at,&gates,stable_eligible))?;Ok(ReleaseEvidence{schema_version:1,version:version.into(),channel:channel.into(),commit:commit.into(),generated_at_ns:at,gates,stable_eligible,evidence_hash:blake3::hash(&b).to_hex().to_string()})}
fn walk(root:&Path,current:&Path,out:&mut Vec<FileEntry>)->Result<(),ReleaseError>{for e in fs::read_dir(current)?{let path=e?.path();let m=fs::symlink_metadata(&path)?;if m.file_type().is_symlink(){return Err(ReleaseError::Unsafe)}if m.is_dir(){walk(root,&path,out)?}else if m.is_file(){let rel=path.strip_prefix(root).map_err(|_|ReleaseError::Unsafe)?;if rel.is_absolute()||rel.components().any(|c|!matches!(c,Component::Normal(_))){return Err(ReleaseError::Unsafe)}let bytes=fs::read(&path)?;#[cfg(unix)]let executable={use std::os::unix::fs::PermissionsExt;m.permissions().mode()&0o111!=0};#[cfg(not(unix))]let executable=false;out.push(FileEntry{path:rel.to_string_lossy().replace('\\',"/"),bytes:m.len(),sha256:hex::encode(Sha256::digest(&bytes)),blake3:blake3::hash(&bytes).to_hex().to_string(),executable})}else{return Err(ReleaseError::Unsafe)}}Ok(())}
#[derive(Debug,Error)]pub enum ReleaseError{#[error("input")]Input,#[error("manifest")]Manifest,#[error("evidence")]Evidence,#[error("unsafe path")]Unsafe,#[error(transparent)]Io(#[from]std::io::Error),#[error(transparent)]Json(#[from]serde_json::Error)}
