use rand_core::{OsRng,RngCore};use serde::{Deserialize,Serialize};use std::{collections::{BTreeMap,BTreeSet},fs::File,io::Read,net::IpAddr};use subtle::ConstantTimeEq;use thiserror::Error;use url::Url;use zeroize::{Zeroize,Zeroizing};
pub const SESSION_HEADER:&str="x-cmti-session-token";pub struct SessionSecret([u8;32]);impl SessionSecret{pub fn random()->Self{let mut b=[0;32];OsRng.fill_bytes(&mut b);Self(b)}pub const fn expose(&self)->&[u8;32]{&self.0}}impl Drop for SessionSecret{fn drop(&mut self){self.0.zeroize()}}
pub struct SessionToken([u8;32]);impl SessionToken{pub fn derive(secret:&SessionSecret,protocol:u32)->Self{let mut b=Vec::from(b"cmti:session:v1\0".as_slice());b.extend_from_slice(&protocol.to_be_bytes());Self(*blake3::keyed_hash(secret.expose(),&b).as_bytes())}pub fn header_value(&self)->String{hex::encode(self.0)}pub fn verify(&self,value:&str)->bool{hex::decode(value).ok().filter(|v|v.len()==32).is_some_and(|v|bool::from(self.0.ct_eq(v.as_slice())))}}impl Drop for SessionToken{fn drop(&mut self){self.0.zeroize()}}
#[cfg(unix)]#[allow(unsafe_code)]pub fn read_secret_fd(fd:std::os::fd::RawFd)->Result<SessionSecret,SecurityError>{use std::os::fd::FromRawFd;if fd<3{return Err(SecurityError::Descriptor)}let file=unsafe{File::from_raw_fd(fd)};let mut bytes=Zeroizing::new(Vec::with_capacity(33));file.take(33).read_to_end(&mut bytes)?;if bytes.len()!=32{return Err(SecurityError::Length)}let mut secret=[0;32];secret.copy_from_slice(&bytes);Ok(SessionSecret(secret))}
#[derive(Clone,Copy,Debug,Eq,Ord,PartialEq,PartialOrd,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum NetworkPurpose{ExchangeMarketData,BitcoinNode,EthereumExecution,EthereumConsensus,ReleaseUpdate}
#[derive(Clone,Debug,Eq,Ord,PartialEq,PartialOrd,Serialize,Deserialize)]pub struct HostRule{pub scheme:String,pub host:String,pub port:Option<u16>}
#[derive(Clone,Debug,Default,Serialize,Deserialize)]pub struct OutboundPolicy{pub rules:BTreeMap<NetworkPurpose,BTreeSet<HostRule>>}
impl OutboundPolicy{pub fn allow(&mut self,purpose:NetworkPurpose,url:&str)->Result<(),SecurityError>{self.rules.entry(purpose).or_default().insert(normalize(url)?);Ok(())}pub fn authorize(&self,purpose:NetworkPurpose,url:&str)->Result<(),SecurityError>{let r=normalize(url)?;if self.rules.get(&purpose).is_some_and(|s|s.contains(&r)){Ok(())}else{Err(SecurityError::OutboundDenied)}}}
fn normalize(v:&str)->Result<HostRule,SecurityError>{let u=Url::parse(v).map_err(|_|SecurityError::Url)?;if !u.username().is_empty()||u.password().is_some()||u.query().is_some()||u.fragment().is_some(){return Err(SecurityError::Url)}let scheme=u.scheme().to_ascii_lowercase();let host=u.host_str().ok_or(SecurityError::Url)?.to_ascii_lowercase();if scheme=="http"&&!host.parse::<IpAddr>().is_ok_and(|ip|ip.is_loopback())&&host!="localhost"{return Err(SecurityError::Url)}if !matches!(scheme.as_str(),"http"|"https"|"wss"){return Err(SecurityError::Url)}Ok(HostRule{scheme,host,port:u.port_or_known_default()})}
#[derive(Debug,Error)]pub enum SecurityError{#[error("unsafe descriptor")]Descriptor,#[error("secret length")]Length,#[error("invalid URL")]Url,#[error("outbound denied")]OutboundDenied,#[error(transparent)]Io(#[from]std::io::Error)}
