use serde::{Deserialize,Serialize};use thiserror::Error;use uuid::Uuid;
#[derive(Clone,Copy,Debug,Eq,PartialEq,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum EventKind{DownsideTransition,UpsideSqueeze,VolatilityExplosion,LiquidityVacuum,LiquidationCascade,BasisDislocation,StablecoinDislocation,Contagion}
#[derive(Clone,Copy,Debug,Eq,PartialEq,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum ForecastStatus{Active,Abstained,Experimental,Suppressed}
#[derive(Clone,Copy,Debug,Eq,PartialEq,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum AbstentionCode{None,InsufficientData,StaleInput,DataQuality,OutOfDistribution,ModelUnavailable,UnsupportedScope}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]pub struct ProbabilityPoint{pub horizon_seconds:u64,pub cumulative_incidence:f64,pub lower_bound:f64,pub upper_bound:f64,pub calibrated_baseline:f64}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]pub struct Uncertainty{pub aleatoric:f64,pub epistemic:f64,pub data:f64,pub method_id:String}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]pub struct ModelLineage{pub model_package_id:String,pub version:String,pub artifact_hash:String,pub feature_schema_hash:String,pub training_cutoff_ns:i64,pub code_commit:String,pub calibration_id:String,pub label_definition_id:String}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]pub struct EvidenceItem{pub feature_id:String,pub value:f64,pub contribution:f64,pub as_known_at_ns:i64,pub provenance_id:String}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]pub struct EvidenceBundle{pub bundle_id:String,pub positive:Vec<EvidenceItem>,pub negative:Vec<EvidenceItem>,pub mechanisms:Vec<String>,pub canonical_hash:String}
#[derive(Clone,Debug,PartialEq,Serialize,Deserialize)]pub struct TransitionForecast{pub forecast_id:Uuid,pub asset:String,pub event:EventKind,pub status:ForecastStatus,pub abstention:AbstentionCode,pub points:Vec<ProbabilityPoint>,pub uncertainty:Uncertainty,pub quality_score_ppm:u32,pub lineage:ModelLineage,pub evidence:EvidenceBundle,pub issued_at_ns:i64,pub as_known_at_ns:i64,pub valid_until_ns:i64,pub request_id:String}
impl TransitionForecast{pub fn validate(&self)->Result<(),RiskError>{if self.asset.is_empty()||self.request_id.is_empty()||self.points.is_empty()||self.quality_score_ppm>1_000_000||self.issued_at_ns>=self.valid_until_ns||self.evidence.canonical_hash.len()!=64||self.points.iter().any(|p|p.horizon_seconds==0||![p.cumulative_incidence,p.lower_bound,p.upper_bound,p.calibrated_baseline].iter().all(|v|v.is_finite()&&(0.0..=1.0).contains(v))||p.lower_bound>p.cumulative_incidence||p.upper_bound<p.cumulative_incidence)||!self.points.windows(2).all(|w|w[0].horizon_seconds<w[1].horizon_seconds&&w[0].cumulative_incidence<=w[1].cumulative_incidence){return Err(RiskError::Invalid)}Ok(())}}
pub fn build(asset:&str,event:EventKind,status:ForecastStatus,abstention:AbstentionCode,points:Vec<ProbabilityPoint>,uncertainty:Uncertainty,quality:u32,lineage:ModelLineage,mut evidence:Vec<EvidenceItem>,mechanisms:Vec<String>,issued:i64,valid_until:i64,request_id:String)->Result<TransitionForecast,RiskError>{if asset.is_empty(){return Err(RiskError::Invalid)}evidence.sort_by(|a,b|b.contribution.abs().total_cmp(&a.contribution.abs()));evidence.truncate(20);let positive=evidence.iter().filter(|x|x.contribution>=0.0).cloned().collect();let negative=evidence.iter().filter(|x|x.contribution<0.0).cloned().collect();let canonical=serde_json::to_vec(&(asset,event,&points,&positive,&negative,&mechanisms))?;let forecast=TransitionForecast{forecast_id:Uuid::now_v7(),asset:asset.into(),event,status,abstention,points,uncertainty,quality_score_ppm:quality,lineage,evidence:EvidenceBundle{bundle_id:Uuid::now_v7().to_string(),positive,negative,mechanisms,canonical_hash:blake3::hash(&canonical).to_hex().to_string()},issued_at_ns:issued,as_known_at_ns:issued,valid_until_ns:valid_until,request_id};forecast.validate()?;Ok(forecast)}
#[derive(Debug,Error)]pub enum RiskError{#[error("invalid forecast")]Invalid,#[error(transparent)]Json(#[from]serde_json::Error)}
