use serde::{Deserialize,Serialize};use serde_json::Value;use std::{collections::BTreeMap,fs,path::Path,sync::{Arc,Mutex}};use thiserror::Error;use tracing_appender::non_blocking::{ErrorCounter,NonBlockingBuilder,WorkerGuard};use tracing_subscriber::util::SubscriberInitExt;
pub const REDACTED:&str="[REDACTED]";
#[derive(Clone,Copy,Debug,Eq,Ord,PartialEq,PartialOrd,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum MetricName{EventsReceived,EventsRejected,SequenceGaps,ChecksumFailures,Reconnects,QueueDepth,WalLatencyMicros,InferenceLatencyMicros,RpcLatencyMicros,AlertsEmitted,Abstentions,DroppedLogLines}
#[derive(Clone,Copy,Debug,Eq,Ord,PartialEq,PartialOrd,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum Component{Ingestion,OrderBook,FeatureEngine,ModelEngine,Rpc,Alerting,Storage,Replay,System}
#[derive(Clone,Copy,Debug,Eq,Ord,PartialEq,PartialOrd,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum Venue{Binance,Bybit,Kraken,Deribit,Other,NotApplicable}
#[derive(Clone,Copy,Debug,Eq,Ord,PartialEq,PartialOrd,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum Outcome{Success,Rejected,Timeout,Degraded,Abstained,NotApplicable}
#[derive(Clone,Copy,Debug,Eq,Ord,PartialEq,PartialOrd,Serialize,Deserialize)]pub struct MetricKey{pub name:MetricName,pub component:Component,pub venue:Venue,pub outcome:Outcome}
#[derive(Clone,Debug)]enum Stored{Counter(u64),Gauge(i64),Histogram{counts:[u64;13],sum:u64,count:u64}}
#[derive(Clone,Default)]pub struct Metrics{inner:Arc<Mutex<BTreeMap<MetricKey,Stored>>>}
const BOUNDS:[u64;12]=[10,25,50,100,250,500,1_000,2_500,5_000,10_000,50_000,250_000];
impl Metrics{pub fn increment(&self,key:MetricKey,amount:u64)->Result<(),ObservabilityError>{let mut map=self.inner.lock().map_err(|_|ObservabilityError::Poisoned)?;match map.entry(key).or_insert(Stored::Counter(0)){Stored::Counter(v)=>{*v=v.saturating_add(amount);Ok(())},_=>Err(ObservabilityError::Type)}}pub fn gauge(&self,key:MetricKey,value:i64)->Result<(),ObservabilityError>{self.inner.lock().map_err(|_|ObservabilityError::Poisoned)?.insert(key,Stored::Gauge(value));Ok(())}pub fn observe(&self,key:MetricKey,value:u64)->Result<(),ObservabilityError>{let mut map=self.inner.lock().map_err(|_|ObservabilityError::Poisoned)?;match map.entry(key).or_insert(Stored::Histogram{counts:[0;13],sum:0,count:0}){Stored::Histogram{counts,sum,count}=>{let i=BOUNDS.iter().position(|b|value<=*b).unwrap_or(BOUNDS.len());counts[i]=counts[i].saturating_add(1);*sum=sum.saturating_add(value);*count=count.saturating_add(1);Ok(())},_=>Err(ObservabilityError::Type)}}}
#[derive(Clone,Default)]pub struct Redactor;impl Redactor{pub fn field(&self,key:&str,value:&str)->String{if sensitive_key(key)||sensitive_value(value){REDACTED.into()}else{sanitize(value)}}pub fn json(&self,value:&Value)->Value{match value{Value::Object(map)=>Value::Object(map.iter().map(|(k,v)|if sensitive_key(k){(k.clone(),Value::String(REDACTED.into()))}else{(k.clone(),self.json(v))}).collect()),Value::Array(v)=>Value::Array(v.iter().take(1024).map(|x|self.json(x)).collect()),Value::String(v)=>Value::String(self.field("value",v)),v=>v.clone()}}}
pub struct LogGuard{_worker:WorkerGuard,counter:ErrorCounter}impl LogGuard{pub fn dropped_lines(&self)->usize{self.counter.dropped_lines()}}
pub fn init_local_json(directory:&Path,level:&str)->Result<LogGuard,ObservabilityError>{fs::create_dir_all(directory)?;#[cfg(unix)]{use std::os::unix::fs::PermissionsExt;fs::set_permissions(directory,fs::Permissions::from_mode(0o700))?}let appender=tracing_appender::rolling::daily(directory,"cmti.jsonl");let(writer,worker)=NonBlockingBuilder::default().buffered_lines_limit(8192).lossy(true).thread_name("cmti-log-writer").finish(appender);let counter=writer.error_counter();let filter=tracing_subscriber::EnvFilter::try_new(level).map_err(|_|ObservabilityError::Level)?;tracing_subscriber::fmt().json().with_writer(writer).with_env_filter(filter).try_init().map_err(|e|ObservabilityError::Subscriber(e.to_string()))?;Ok(LogGuard{_worker:worker,counter})}
fn sensitive_key(k:&str)->bool{let k=k.to_ascii_lowercase();["password","secret","token","authorization","cookie","api_key","private_key","credential","session"].iter().any(|v|k.contains(v))}
fn sensitive_value(v:&str)->bool{let l=v.to_ascii_lowercase();l.contains("bearer ")||l.contains("password=")||l.contains("api_key=")||l.starts_with("keychain://")||contains_json_secret(v)}
fn contains_json_secret(v:&str)->bool{serde_json::from_str::<Value>(v).ok().is_some_and(|x|match x{Value::Object(ref m)=>m.keys().any(|k|sensitive_key(k))||m.values().any(|v|contains_json_secret(&v.to_string())),Value::Array(ref a)=>a.iter().any(|v|contains_json_secret(&v.to_string())),_=>false})}
fn sanitize(v:&str)->String{v.chars().map(|c|if c.is_control(){' '}else{c}).take(4096).collect()}
#[derive(Debug,Error)]pub enum ObservabilityError{#[error("metric type mismatch")]Type,#[error("poisoned metrics")]Poisoned,#[error("invalid level")]Level,#[error("subscriber: {0}")]Subscriber(String),#[error(transparent)]Io(#[from]std::io::Error)}
