//! Symlink-safe atomic checkpoint and encrypted backup recovery.
use chacha20poly1305::{XChaCha20Poly1305,XNonce,aead::{Aead,KeyInit,Payload}};use rand_core::{OsRng,RngCore};use serde::{Deserialize,Serialize};use std::{fs::{self,File,OpenOptions},io::Write,path::Path};use thiserror::Error;use uuid::Uuid;use zeroize::Zeroizing;
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct Checkpoint{pub schema_version:u32,pub checkpoint_id:Uuid,pub created_at_ns:i64,pub code_commit:String,pub configuration_hash:String,pub wal_segment:u64,pub wal_offset:u64,pub payload_hash:String,pub payload:Vec<u8>}
impl Checkpoint{pub fn new(created:i64,commit:String,config:String,segment:u64,offset:u64,payload:Vec<u8>)->Result<Self,RecoveryError>{if payload.is_empty()||payload.len()>512*1024*1024||commit.len()<7||config.len()!=64{return Err(RecoveryError::Checkpoint)}Ok(Self{schema_version:1,checkpoint_id:Uuid::now_v7(),created_at_ns:created,code_commit:commit,configuration_hash:config,wal_segment:segment,wal_offset:offset,payload_hash:blake3::hash(&payload).to_hex().to_string(),payload})}pub fn verify(&self)->Result<(),RecoveryError>{if self.schema_version==1&&self.payload_hash==blake3::hash(&self.payload).to_hex().to_string(){Ok(())}else{Err(RecoveryError::Integrity)}}}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct BackupEnvelope{pub schema_version:u32,pub backup_id:Uuid,pub created_at_ns:i64,pub nonce:[u8;24],pub associated_data_hash:String,pub ciphertext:Vec<u8>,pub ciphertext_hash:String}
pub fn encrypt_backup(key:[u8;32],created:i64,aad:&[u8],plain:&[u8])->Result<BackupEnvelope,RecoveryError>{if plain.is_empty(){return Err(RecoveryError::Capacity)}let key=Zeroizing::new(key);let cipher=XChaCha20Poly1305::new((&*key).into());let mut nonce=[0;24];OsRng.fill_bytes(&mut nonce);let ciphertext=cipher.encrypt(XNonce::from_slice(&nonce),Payload{msg:plain,aad}).map_err(|_|RecoveryError::Crypto)?;Ok(BackupEnvelope{schema_version:1,backup_id:Uuid::now_v7(),created_at_ns:created,nonce,associated_data_hash:blake3::hash(aad).to_hex().to_string(),ciphertext_hash:blake3::hash(&ciphertext).to_hex().to_string(),ciphertext})}
pub fn decrypt_backup(key:[u8;32],aad:&[u8],e:&BackupEnvelope)->Result<Zeroizing<Vec<u8>>,RecoveryError>{if e.schema_version!=1||e.associated_data_hash!=blake3::hash(aad).to_hex().to_string()||e.ciphertext_hash!=blake3::hash(&e.ciphertext).to_hex().to_string(){return Err(RecoveryError::Integrity)}let key=Zeroizing::new(key);let cipher=XChaCha20Poly1305::new((&*key).into());Ok(Zeroizing::new(cipher.decrypt(XNonce::from_slice(&e.nonce),Payload{msg:&e.ciphertext,aad}).map_err(|_|RecoveryError::Crypto)?))}
pub fn store_checkpoint(path:&Path,c:&Checkpoint)->Result<(),RecoveryError>{c.verify()?;let parent=path.parent().ok_or(RecoveryError::Unsafe)?;fs::create_dir_all(parent)?;if fs::symlink_metadata(parent)?.file_type().is_symlink(){return Err(RecoveryError::Unsafe)}let temp=parent.join(format!(".{}.tmp",Uuid::now_v7()));let mut o=OpenOptions::new();o.create_new(true).write(true);#[cfg(unix)]{use std::os::unix::fs::OpenOptionsExt;o.mode(0o600);}let mut f=o.open(&temp)?;f.write_all(&serde_json::to_vec(c)?)?;f.sync_all()?;fs::rename(&temp,path)?;#[cfg(unix)]{File::open(parent)?.sync_all()?}Ok(())}
#[derive(Debug,Error)]pub enum RecoveryError{#[error("invalid checkpoint")]Checkpoint,#[error("integrity failure")]Integrity,#[error("capacity")]Capacity,#[error("unsafe path")]Unsafe,#[error("cryptography")]Crypto,#[error(transparent)]Io(#[from]std::io::Error),#[error(transparent)]Json(#[from]serde_json::Error)}
