use ed25519_dalek::{Signature,Signer,SigningKey,Verifier,VerifyingKey};use serde::{Deserialize,Serialize};use std::collections::{BTreeMap,BTreeSet};use thiserror::Error;use zeroize::{Zeroize,Zeroizing};
#[derive(Clone,Copy,Debug,Eq,Ord,PartialEq,PartialOrd,Serialize,Deserialize)]#[serde(rename_all="snake_case")]pub enum KeyRole{ModelPackage,ApplicationRelease,UpdateManifest,BackupManifest}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct SignedArtifact{pub schema_version:u32,pub role:KeyRole,pub channel:String,pub key_id:String,pub created_at_ns:i64,pub payload_blake3:String,pub signature_hex:String}
#[derive(Clone,Debug,Eq,PartialEq,Serialize,Deserialize)]pub struct TrustedKey{pub key_id:String,pub role:KeyRole,pub public_key_hex:String,pub valid_from_ns:i64,pub valid_until_ns:i64,pub channels:BTreeSet<String>,pub revoked_at_ns:Option<i64>}
#[derive(Clone,Debug,Default,Serialize,Deserialize)]pub struct TrustRegistry{pub keys:BTreeMap<String,TrustedKey>}
pub fn sign(secret:[u8;32],role:KeyRole,channel:&str,key_id:&str,created:i64,payload:&[u8])->Result<SignedArtifact,SigningError>{if channel.is_empty()||key_id.is_empty()||payload.is_empty(){return Err(SigningError::Input)}let secret=Zeroizing::new(secret);let key=SigningKey::from_bytes(&secret);let hash=blake3::hash(payload).to_hex().to_string();let message=message(role,channel,key_id,created,&hash);let sig=key.sign(&message);Ok(SignedArtifact{schema_version:1,role,channel:channel.into(),key_id:key_id.into(),created_at_ns:created,payload_blake3:hash,signature_hex:hex::encode(sig.to_bytes())})}
pub fn verify(a:&SignedArtifact,payload:&[u8],registry:&TrustRegistry,now:i64)->Result<(),SigningError>{if a.schema_version!=1||a.payload_blake3!=blake3::hash(payload).to_hex().to_string(){return Err(SigningError::Integrity)}let k=registry.keys.get(&a.key_id).ok_or(SigningError::Untrusted)?;if k.role!=a.role||!k.channels.contains(&a.channel)||a.created_at_ns<k.valid_from_ns||a.created_at_ns>k.valid_until_ns||now<k.valid_from_ns||now>k.valid_until_ns||k.revoked_at_ns.is_some_and(|t|a.created_at_ns>=t){return Err(SigningError::Policy)}let public:[u8;32]=hex::decode(&k.public_key_hex).map_err(|_|SigningError::Encoding)?.try_into().map_err(|_|SigningError::Encoding)?;let signature:[u8;64]=hex::decode(&a.signature_hex).map_err(|_|SigningError::Encoding)?.try_into().map_err(|_|SigningError::Encoding)?;VerifyingKey::from_bytes(&public).map_err(|_|SigningError::Encoding)?.verify(&message(a.role,&a.channel,&a.key_id,a.created_at_ns,&a.payload_blake3),&Signature::from_bytes(&signature)).map_err(|_|SigningError::Signature)}
pub fn public_key(mut secret:[u8;32])->String{let key=SigningKey::from_bytes(&secret);let value=hex::encode(key.verifying_key().to_bytes());secret.zeroize();value}
fn message(role:KeyRole,channel:&str,key_id:&str,created:i64,hash:&str)->Vec<u8>{let mut b=Vec::from(b"cmti:signed-artifact:v1\0".as_slice());b.push(role as u8);for s in[channel,key_id,hash]{b.extend_from_slice(&(s.len()as u32).to_be_bytes());b.extend_from_slice(s.as_bytes())}b.extend_from_slice(&created.to_be_bytes());b}
#[derive(Debug,Error)]pub enum SigningError{#[error("input")]Input,#[error("integrity")]Integrity,#[error("untrusted")]Untrusted,#[error("policy")]Policy,#[error("encoding")]Encoding,#[error("signature")]Signature}
